server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          loverCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/**
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/v1/wallets/**
        - id: journal-service
          uri: lb://journal-service
          predicates:
            - Path=/api/v1/journals/**
        - id: expenses-service
          uri: lb://expenses-service
          predicates:
            - Path=/api/v1/expenses/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true