server:
  port: 8084

spring:
  application:
    name: expenses-service
  r2dbc:
    url: r2dbc:postgresql://localhost/expenses_serv_db
    username: postgres
    password: YOUR_PASSWORD
  data:
    r2dbc:
      repositories:
        enabled: true
  flyway:
    url: jdbc:postgresql://localhost:5432/expenses_serv_db
    user: postgres
    password: YOUR_PASSWORD
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/