server:
  port: 8082

spring:
  application:
    name: wallet-service
  r2dbc:
    url: r2dbc:postgresql://localhost/wallet_serv_db
    username: postgres
    password: YOUR_PASSWORD
  data:
    r2dbc:
      repositories:
        enabled: true
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/